import Head from "next/head";
import estilos from "@/styles/Home.module.css";
import Topo from "@/componentes/Topo";
import Card from "@/componentes/card";
import Rodape from "@/componentes/Rodape";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Topo/>
      <main>
        <section className={estilos.secao_cards}>
        <Card/>
        <Card/>
        <Card/>
        </section>
        <Rodape/>

      </main>
    </>
  );
}
